# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBetterBranch < Formula
  desc "A better git branch viewer for repositories with long branch names, worktrees, and many remotes"
  homepage "https://github.com/redodson01/git-better-branch"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.1/git-better-branch_0.1.1_darwin_amd64.tar.gz"
      sha256 "f200362ff553f494d25bc423b353edffb5b2362a9bbf82abf0ae9e22249c7674"

      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.1/git-better-branch_0.1.1_darwin_arm64.tar.gz"
      sha256 "844c800916789990631ca12e1c4212598284fb1b07c90d526e04eea273a50c22"

      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.1/git-better-branch_0.1.1_linux_amd64.tar.gz"
      sha256 "850c019b6655ed1c687c2fbf78f80dc525ce50fac382a3a7eca26ac233bce6c9"
      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.1/git-better-branch_0.1.1_linux_arm64.tar.gz"
      sha256 "db6dfdae074a7c0862dc1ccf22f9c4e51f13812c731553088b64e3b55677fa12"
      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
  end

  test do
    system bin/"git-better-branch", "--version"
  end
end
