# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBetterBranch < Formula
  desc "A better git branch viewer for repositories with long branch names, worktrees, and many remotes"
  homepage "https://github.com/redodson01/git-better-branch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.0/git-better-branch_0.1.0_darwin_amd64.tar.gz"
      sha256 "4caaca19a520a664dae6f8204119112e5cf267299359ec51b65c2de8a3eea3a7"

      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.0/git-better-branch_0.1.0_darwin_arm64.tar.gz"
      sha256 "20f457218d8e9b8f7a5ab928bdda200d30b73d714cf57468239f932134efb9b8"

      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.0/git-better-branch_0.1.0_linux_amd64.tar.gz"
      sha256 "248bc3754511fe56117819236321e17361e86c37b5a626bb442084dbe3493e92"
      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redodson01/git-better-branch/releases/download/v0.1.0/git-better-branch_0.1.0_linux_arm64.tar.gz"
      sha256 "ee72bfcbd8d85a4c5493aeb853174577814a5e538d1b15bb29db9bab563fa6c3"
      define_method(:install) do
        bin.install "git-better-branch"
      end
    end
  end

  test do
    system bin/"git-better-branch", "--version"
  end
end
